### ISSUE TITLE
How to install/use software?

### ISSUE THREAD

**Issue by TunderTunder** [Bosek/OstrivSDK#2]

**Comment by Bosek** [comment]
Hello,
 everything needed should be in [Readme](https://github.com/Bosek/OstrivSDK/blob/master/README.md), you can download the thing from [Releases](https://github.com/Bosek/OstrivSDK/releases/), you want to download `ostrivsdk.zip`.

The tool is primarily used via command line. Pay attention to **OstrivConverter** section of the Readme.
